### ISSUE TITLE
Tracking issue: CloudScape CSS styles may differ in client and cause layout shifts

### ISSUE THREAD

**Issue by cardoso** [bitmovin/amazon-ivs-analytics-demo#3]
In the server the layout may be rendered with different sizes for certain elements than on the client due to media queries. 

I've been able to work around most of these issues by overriding some CSS styles in globals.css to avoid layout shifts in hydration:

```scss
.awsui-context-top-navigation>header>div {
    height: 48px !important;
    padding-left: 20px !important;

    div>a>img {
        height: 24px !important;
    }
}

// some class names need to be matched due to css modules name mangling
[class*="awsui_offset-right-xxl"] {
    margin-right: 12px !important;
}
.chart-container {
    padding-top: 20px !important;
}
```
